/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class work_tinax_midij_play_OSDirectDevice */

#ifndef _Included_work_tinax_midij_play_OSDirectDevice
#define _Included_work_tinax_midij_play_OSDirectDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     work_tinax_midij_play_OSDirectDevice
 * Method:    getDeviceNames
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_work_tinax_midij_play_OSDirectDevice_getDeviceNames
  (JNIEnv *, jobject);

/*
 * Class:     work_tinax_midij_play_OSDirectDevice
 * Method:    openDevice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_work_tinax_midij_play_OSDirectDevice_openDevice__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     work_tinax_midij_play_OSDirectDevice
 * Method:    openDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_work_tinax_midij_play_OSDirectDevice_openDevice__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     work_tinax_midij_play_OSDirectDevice
 * Method:    closeDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_work_tinax_midij_play_OSDirectDevice_closeDevice
  (JNIEnv *, jobject);

/*
 * Class:     work_tinax_midij_play_OSDirectDevice
 * Method:    getCurrentPortName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_work_tinax_midij_play_OSDirectDevice_getCurrentPortName
  (JNIEnv *, jobject);

/*
 * Class:     work_tinax_midij_play_OSDirectDevice
 * Method:    getApiName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_work_tinax_midij_play_OSDirectDevice_getApiName
  (JNIEnv *, jobject);

/*
 * Class:     work_tinax_midij_play_OSDirectDevice
 * Method:    sendMessage
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_work_tinax_midij_play_OSDirectDevice_sendMessage
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
